In [1]:
#here we are the predicting the price of the home based on the area,badrooms,ageofhome 
#so our dependent variable is price and our independent variable is bedrooms,age,area
#if we are looking at equation then our equation may look like 
#price=m1*area+m2*bedrooms+m3*age+b b is intercept and m is coefficient


In [14]:
import pandas as  pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')


In [17]:
df=pd.read_csv('homeprices.csv')
df.shape

(6, 4)

In [4]:
#now we will fill the null value by using median of bedrooms
#here math.floor function is used to round up the decimal part
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
df['bedrooms']=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg=linear_model.LinearRegression()


In [7]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540384

In [10]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [11]:
#as we write equation already so by that equation we will varify the value
3000*112.06244194+3*23388.88007794+40*(-3231.71790863)+221323.00186540384

498408.25157402386

In [12]:
reg.predict([[2500,4,5]])

array([578876.03748933])